name: caller
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.0.1

flutter:

ffigen:
  name: NativeLibrary
  description: Bindings to `../adder/adder.h`.
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      - '../adder/adder.h'
